# Target Python version
target-version = "py312"
line-length = 100

[lint.isort]
known-first-party = ["app"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = ["ALL"]

ignore = [
    "E501",
    "COM812",
    "ISC001",
    "D1",
    "D203",
    "D213",
    "TD",
    "FIX",
    "ERA",
    "CPY",
    "FBT",
]

[lint.per-file-ignores]
"alembic/*" = ["INP001", "D205"]
"tests/**/*" = [
    "S101",
    "S105",
    "S106",
    "ANN",
    "PLR2004",
    "D",
]
