"""add created_at to project_members.

Revision ID: 51dbcf5919b2
Revises: 3c4d5e6f7a8b
Create Date: 2026-03-23 21:05:17.860092

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51dbcf5919b2"
down_revision: str | Sequence[str] | None = "3c4d5e6f7a8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_members",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("ux_project_members_owner_per_project"),
        table_name="project_members",
        postgresql_where="(role = 'owner'::project_member_role)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ux_project_members_owner_per_project"),
        "project_members",
        ["project_id"],
        unique=True,
        postgresql_where="(role = 'owner'::project_member_role)",
    )
    op.drop_column("project_members", "created_at")
    # ### end Alembic commands ###
